# ===============================
# DATABASE CONFIGURATION
# ===============================
# We add ?createDatabaseIfNotExist=true so that MySQL automatically creates our 'student_management_db' for us!
spring.datasource.url=jdbc:mysql://localhost:3306/student_management_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Deepak@2002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# HIBERNATE (JPA) CONFIGURATION
# ===============================
# update: This command tells Hibernate to automatically create or update our database tables to match our Java code. 
spring.jpa.hibernate.ddl-auto=update

# True: Forces the console to print out the raw SQL statements Hibernate is generating behind the scenes. Great for learning!
spring.jpa.show-sql=true

# True: Neatly formats those printed SQL statements instead of printing them on one ugly line.
spring.jpa.properties.hibernate.format_sql=true

# Tells our embedded Tomcat server what port to run our application on. 8080 is the standard.
server.port=8080
